Edits
mahmutovAR/imagesort pull request #3
Opened 2021-12-03 18:58 UTC by mahmutovAR

документация функций не исправлена, сначала надо привести аргументы и функции в порядок

сейчас скрипт берет все файлы из initial folder и делит на группы:
- изображения (по расширению)
- не изображения (по расширению)
- изображения у которых не вычисляется размер

при копировании проверяется название файла в соответствующей папке в target folder:
- если названия совпадают и совпадают контрольные суммы, файл не копируется
- если названия совпадают, а контрольные суммы нет - переименовывается копируемый файл и проверка повторяется
    переименование выглядит так: перед старым названием добавляется !1, если такой файл существует, то !2 и т.д.

в режиме dryrun - в готовых папках указывается исходное название без проверки названий файлов

если проверка контрольных сумм после сортировки не прошла успешно, то удаление файлов из initial folder отменяется
(соответствующее сообщение появляется в консоли)

вопрос по коду:

- перемещение файлов реализовано так:
   1 копирование файлов
   2 удаление папки initial_folder
   3 создание папки initial_folder
	это сильно криво?
	python позволяет сделать как сейчас реализовано, или
        сначала удалить все файлы из всех папок, а потом уже удалить все пустые папки

вопросы по функционалу:

- если один и тот же файл содержится в разных папках с разными именами - необходимо ли удалять клона?

- нужен ли в консоли отчет после верификации? (всего __ файлов, __ изображений, __ не изображений....)

- какой лучше указать размер буфера при вычислении контрольной суммы? сейчас block_size = 65536

2021-12-05 10:17 UTC, starichkovva commented
> если один и тот же файл содержится в разных папках с разными именами - необходимо ли удалять клона?

Алгоритм проверки контрольной суммы не даёт стопроцентной гарантии идентичности файлов при идентичных хэш-суммах, я бы сказал клон нужно класть рядом добавляя суффикс к названию.

> нужен ли в консоли отчет после верификации? (всего __ файлов, __ изображений, __ не изображений....)

Почему бы и нет, это же консольная утилита получается, пусть будет.

> какой лучше указать размер буфера при вычислении контрольной суммы? сейчас block_size = 65536

Это сложный вопрос, потому как оптимальный, с точки зрения производительности, размер буфера зависит как от конкретной модели жёсткого диска или SSD, так и от текущей файловой системы на этом диске.

Можно либо оставить 64 килобайта как сейчас, либо сделать этот параметр настраиваемым, оставив значение по умолчанию в 64 килобайта.

2021-12-05 10:20 UTC, starichkovva commented
> перемещение файлов реализовано так:
1 копирование файлов
2 удаление папки initial_folder
3 создание папки initial_folder
это сильно криво?

Честно говоря не совсем понял из описания как же оно всё-таки реализовано. Но советую посмотреть [на вот эту библиотеку](https://docs.python.org/3.9/library/shutil.html), входящую в стандартный набор.

2021-12-05 12:21 UTC, mahmutovAR commented
> > перемещение файлов реализовано так:
> 1 копирование файлов
> 2 удаление папки initial_folder
> 3 создание папки initial_folder
> это сильно криво?
> 
> Честно говоря не совсем понял из описания как же оно всё-таки реализовано. Но советую посмотреть [на вот эту библиотеку](https://docs.python.org/3.9/library/shutil.html), входящую в стандартный набор.

При выборе режима "копирование" - файлы копируются, при выборе режима "по умолчанию" - файлы копируются[1], и только после успешной верификации файлов по контрольным суммам, сама папка initial folder удаляется[2] (со всем содержимым соответственно), и после этого создаётся новая папка с прежним названием[3]. Это криво потому, что зачем удалять саму папку, если можно удалить все папки и файлы внутри неё. Но вот реализовать нормальный способ сейчас можно так:
- заходишь во все папки по очереди,
- удаляются все файлы внутри,
- а уже потом удаляется все пустые папки
Поэтому я выбрал кривой, но не быстрый путь

2021-12-05 12:35 UTC, starichkovva commented
А зачем тебе исходная пустая папка после перемещения всех файлов?

2021-12-05 18:23 UTC, mahmutovAR commented
В принципе если все прошло успешно и все файлы раскиданы в другой папке - можно и удалить.
Еще два вопроса появилось:
1. После твоего уточнения: "...Алгоритм проверки контрольной суммы не даёт стопроцентной гарантии идентичности файлов при идентичных хэш-суммах..."
- если в папке "600х400" лежит картинка "wall_1.bmp" и скрипт пытается туда скопировать "wall_1.bmp" с идентичной хэш-суммой, то лучше сохранить оба варианта? Сейчас данный файл просто не будет скопирован.
2. Пожалуй стоит добавить проверку на совпадение initial folder и target folder - иначе по итогу все будет рассортировано, а потом благополучно удалено. Согласен?

2021-12-06 10:55 UTC, starichkovva commented
> если в папке "600х400" лежит картинка "wall_1.bmp" и скрипт пытается туда скопировать "wall_1.bmp" с идентичной хэш-суммой, то лучше сохранить оба варианта? Сейчас данный файл просто не будет скопирован.

Я бы сохранял оба, на манер Windows которая добавляет (1), (2), e.t.c. к имени файлов

2021-12-06 10:56 UTC, starichkovva commented
> Пожалуй стоит добавить проверку на совпадение initial folder и target folder - иначе по итогу все будет рассортировано, а потом благополучно удалено. Согласен?

Да, я думаю это будет один из основных сценариев использования - навести порядок в той же самой папке. Так что программа должна разгрести завалы удалив пустые папки ничего не потеряв.

2021-12-12 18:56 UTC, starichkovva commented
Давай всё-таки займемся оформлением этого проекта в GitHub:

- Завести Project на вкладке Projects как описано [в официальной доке](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards) GitHub-а
- Создать под новый проект команду
- Назначить в команду меня и @zaharov-k

2021-12-12 19:33 UTC, starichkovva commented on imagesort.py
> +    initial_folder, target_folder, folder_rename_status, remove_status, dry_run, all_files, images, not_images_status, not_images = parse_arguments(image_types)
Давай добавим следующую обёртку - если число аргументов неправильное или недостаточное для продолжения работы - печатать на экран справочную информацию о том, как правильно использовать этот скрипт.

Обычно принято добавлять специальные аргументы вида `-h` или `--help` для вывода справочной информации.

2021-12-12 19:33 UTC, starichkovva commented on imagesort.py
> +    not_verified = True
Это объявление переменной как будто бы лишнее.

2021-12-12 19:33 UTC, starichkovva commented on imagesort.py
> +        remove_status = False
Как и вот это - не вижу чтобы эта переменная использовалась в коде ниже.

2021-12-12 19:33 UTC, starichkovva commented on imagesort.py
> +        total_not_images+=len(not_images[k])
Много проблем с форматированием кода - нет пробелов в выражении между переменной и операцией. Рекомендую вызвать `Code > Reformat Code` в PyCharm для автоматического исправления подобных моментов.

2021-12-12 19:33 UTC, starichkovva commented on imagesort.py
> +def get_dirs_and_files(folder: str) -> dict:
Хотелось бы видеть документацию на все методы.

2021-12-12 19:33 UTC, starichkovva commented on README.md
>  * copy - sorts images and copies them to the target folder
```
$ python3 imagesort.py ~/dev/walls/ ~/dev/wallpapers dryrun
Error! Entered target folder doesn't exist: /home/starichkov/dev/wallpapers
```
Было бы удобно, если бы скрипт создавал target folder, а не бил по рукам. Мы всё-таки делаем задачу по автоматизации действий.

2021-12-12 19:33 UTC, starichkovva commented on README.md
Если по умолчанию скрипт вызывается в режиме перемещения файлов, то рекомендую параметр для выбора режима делать опциональным. Если не указан - default, если указан - то использовать тот режим что указали.

Иначе получается странная запись вида:

```
$ python3 imagesort.py ~/dev/walls2/ ~/dev/walls2/ default
```

где `default` в конце явно не очень смотрится.

2021-12-12 19:33 UTC, starichkovva commented on imagesort.py
> +            rename_target_folder(initial_folder, target_folder, dir_path)
Если указать скрипту одну и ту же папку как исходную и конечную, скрипт в конце умирает:

```
$ python3 imagesort.py ~/dev/walls2/ ~/dev/walls2/ default
Input parameters are:
Initial folder: /home/***/dev/walls2/
Target folder:  /home/***/dev/walls2/-temp1
Additional option:      sort image and move from the initial folder to the target folder

Information! There is(are) "not images" file(s) in the initial folder so directory "Other files" will be created.
Checksum verification completed successfully
"ImageSort" report:
Total files in the initial folder               938
Images in the initial folder                    919
Not images in the initial folder                19
Not sized images in the initial folder          0
Traceback (most recent call last):
  File "/home/***/imagesort.py", line 317, in <module>
    main()
  File "/home/***/imagesort.py", line 29, in main
    rename_target_folder(initial_folder, target_folder, dir_path)
  File "/home/***/imagesort.py", line 255, in rename_target_folder
    os.rename(target_folder, initial_folder)
FileNotFoundError: [Errno 2] No such file or directory: '/home/***/dev/walls2/-temp1' -> '/home/***/dev/walls2/'```

2022-04-24 18:44 UTC, starichkovva requested changes

2022-05-08 19:39 UTC, mahmutovAR commented on imagesort.py
> +                                                    for attributes in images_attributes.values()])}
заменил генератор словаря на циклы

2022-05-08 19:40 UTC, mahmutovAR commented on imagesort.py
> +                    for resolution in images_by_resolutions.keys()}
заменил генератор словаря на циклы

2022-05-08 19:41 UTC, mahmutovAR commented on imagesort.py
> +    sorted_output_files = {k: sorted(output_files[k])
заменил генератор словаря на циклы

2022-07-04 09:17 UTC, starichkovva commented
Давай смёржим это всё в мастер, чтобы была одна актуальная ветка, по которой я отмечу уже code style моменты.

2022-07-04 18:19 UTC, merged